### ISSUE TITLE
Enhance readme & Add Learn.md

### ISSUE THREAD

**Issue by aasthakourav20** [vishavsingla/Capstone-Anti-Corruption-TTF#43]
Readme file is very important for an project  to get updated as per the changes taking place , 
Kindly assign this issue to me under GSSoC'24

**Comment by ananyabansal16** [comment]
A Readme file is of great importance for a project. Kindly assign this issue to me under GSSoC'24

**Comment by vishavsingla** [comment]
Hi, Please make the relevant changes that you find beneficial and submit pull requests. We will review and merge them if they align with the project objectives.
