### ISSUE TITLE
Update README File

### ISSUE THREAD

**Issue by Ojas-Arora** [vishavsingla/Capstone-Anti-Corruption-TTF#49]
@vishavsingla I want to add some new features to the README File.Kindly assign this issue to me.

**Comment by Ojas-Arora** [comment]
@vishav-singla Can I start working on this issue?

**Comment by vishavsingla** [comment]
@Ojas-Arora Hey please don't waste your and mine time in Readme changes. Make some real contribution would be better for you!

**Comment by Ojas-Arora** [comment]
Ok will try to see another issue.
