### ISSUE TITLE
Improving security and gas efficiency of the smart contracts.

### ISSUE THREAD

**Issue by Vedantjn** [vishavsingla/Capstone-Anti-Corruption-TTF#50]
I made these changes in the smart contracts:

ChallanManagement.sol:
1). Replaced assembly parsing with a more gas-efficient method.
2). Used block.timestamp for issue dates instead of block.number.
3). Added visibility specifiers for all functions.

LandRegistry.sol:
1). Replaced assembly parsing with a more gas-efficient method.
2). Added checks to ensure land is registered before transferring.
3). Added visibility specifiers for all functions.

VehicleManagement.sol:
1). Replaced assembly parsing with a more gas-efficient method.
2). Added visibility specifiers for all functions.

**Comment by vishavsingla** [comment]
Hello @Vedantjn ,
Thanks for the contributions, but actually we are using these contracts in website frontend part, we will have to make changes in that also, I am assigning you the issue, to once setup frontend and check if everything is working fine with updated contracts.

**Comment by Vedantjn** [comment]
Sure.

**Comment by samr874** [comment]
Is the contribution still active ?? are we looking towards more contributions in this project ??

**Comment by vishavsingla** [comment]
Yes. We are looking to improve frontend and bugs in blockchain, you can try setting it up.

**Comment by samr874** [comment]
Sure

**Comment by Vedantjn** [comment]
It is working fine with the updated smart contracts with added security. You can review it. Btw, how to add the gssoc label to this?
