### ISSUE TITLE
What is the required timeline for the redesigned UI

### ISSUE THREAD

**Issue by samr874** [vishavsingla/Capstone-Anti-Corruption-TTF#52]
Tell me the timeline for the UI . 
I am creating one branch separately named as UI2.0 I want to understand the timeline for this project ?
So that I can show you the dummy UI for reference using json server for reference purpose so that we can modify the application?

**Comment by samr874** [comment]
Additionally I am looking towards mobile application extension for this application. I am an experienced React Native developer .I can contribute a mobile application as well as per requirement?

**Comment by vishavsingla** [comment]
@samr874 There is no specific timeline for UI, we want our React pages to look modular and good by end of this week if possible for you. You can share the images with the Pull Request you will make.

@SAMIVo007 can help you with details about React Native Application and additions required for that... You can set it up locally and run it.

**Comment by samr874** [comment]
@vishavsingla Sure noted will look towards the following task by the weekend

- [ ] Understanding the features as per the requirements
